name: Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: '--max_old_space_size=8192'
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Deps
        run: |
          pnpm install

      - name: Build, run tests and lint
        run: |
          pnpm run build
#          pnpm run test
#          pnpm run lint
